name: System Library Build

on:
  push:
    branches:
    - develop
    - master
    - release/*
  pull_request:
    branches:
    - develop
    - master
    - release/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      uses: php-actions/composer@v6
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.json') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      uses: php-actions/composer@v6
      with:
        args: --optimize-autoloader

    - name: PHPUnit Tests
      uses: php-actions/phpunit@v3
      with:
        php_extensions: xdebug
        bootstrap: vendor/autoload.php
        configuration: etc/build
        testsuite: complete
      env:
        XDEBUG_MODE: coverage
